name = "vallefort"
main = "worker.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "KV"
id      = "d2cf4c59c6014806aa2363a9ab0c907e"

[vars]
DISCORD_REDIRECT_URI = "https://vallefort.brede-espelid.workers.dev/auth/callback"
SITE_ORIGIN          = "https://bredeespelid.github.io"
